### ISSUE TITLE
It seems this add-on does not work on Ubuntu

### ISSUE THREAD

**Issue by qqlovekerry** [mganss/AttachFromClipboard#2]
Hi, I am using Thunderbird on Ubuntu, I tried this add-on today but it seems this does not work well on Ubuntu. When I used `From Clipboard`, the attachment is not the file itself, but instead of a text file with the content of the absolute directory of the copied file.
Do I miss something? Or this add-on only works for Thunderbird on Windows?
Any help would be much appreciated!

**Comment by mganss** [comment]
I haven't tested on Linux. There is no Windows-specific code in the add-on so it *should* work on Linux and macOS. I don't have the time currently to investigate further, so any help in tracking this down is appreciated.

- Have you copied an image from another application (e.g. right-click on an image in the browser and choose "copy image")?
- What is the name of the text file that gets attached? When the "flavor" of data on the clipboard (i.e. the MIME type) is `text/unicode` or `text/plain`, the add-on creates a file called `document.txt` with the text content and attaches it.

**Comment by qqlovekerry** [comment]
Hi, thanks for your reply!
- I have tested to copy an image from the browser and in this case it is fine, it works very well with the add-on, after `From Clipboard` is clicked an image named `image.png` is attached in TB
- I am sorry I did not know much about MIME type, but when I copied a PDF file or an image from the folder in my Ubuntu, the attached file is named `document.txt` which contains the directory of the copied file. I think it is as the same as you described. I also attached one example file. Please see that if you think it is necessary.
[document.txt](https://github.com/mganss/AttachFromClipboard/files/2792034/document.txt)

**Comment by mganss** [comment]
When a file is on the clipboard, it is supposed to have the flavor `application/x-moz-file`. This doesn't seem to be the case here. Does dragging from the file manager work?

**Comment by qqlovekerry** [comment]
Yes, I think to drag and drop the file to attach it in TB works well. This function is natively supported by TB, is that right?

**Comment by mganss** [comment]
Yes, drag and drop is natively supported. This may be related to https://bugzilla.mozilla.org/show_bug.cgi?id=992633

Could you try and step into the code here?https://github.com/mganss/AttachFromClipboard/blob/2a69751ab4feaa52c3f3c455f1f36201acc820ee/clipboard%40ganss.org/chrome/content/overlay.js#L114

and see what the value of `data.flavor` is? I'd be surprised if it wasn't `text/plain` or `text/unicode`.
Could you also try using a different file manager?

**Comment by qqlovekerry** [comment]
I am really sorry I do not know how to use that code. Could you please me some instructions?
I search a bit and installed `Dolphin` file manager on my Ubuntu, it fails with an error when I use `From Clipboard` in TB. I got the screenshot, please check that. It seems the other kinds of file manager is not that handy to install on Ubuntu, so I am sorry I did not test the others.
![dolphin](https://user-images.githubusercontent.com/16799190/51749011-21ea9000-20e9-11e9-8f40-e11118106aeb.png)

**Comment by qqlovekerry** [comment]
Hi, I also tried two more file managers in Ubuntu.
1. **Nemo**: The result is as the same as that in the default file manager of Ubuntu -- _Nautilus_, a file named _document.txt_ is attached with the content of the absolute directory of the copied file.
1. **PCManFM**: Nothing happened when I clicked `From Clipboard`.
Hope it helps.

**Comment by mganss** [comment]
I've managed to get it to work. On Linux, files get copied to the clipboard as a list of file URIs (MIME type text/uri-list). You can check what's on the clipboard using

```
xclip -o -t TARGETS -selection clipboard
```

This will list the available MIME types for the current clipboard contents, e.g.

```
TIMESTAMP
TARGETS
MULTIPLE
x-special/gnome-copied-files
text/uri-list
UTF8_STRING
COMPOUND_TEXT
TEXT
STRING
text/plain;charset=utf-8
text/plain
```

You can show the clipboard contents in a specific MIME type using

```
xclip -o -t text/uri-list -selection clipboard
```

This will show e.g.

```
file:///home/user/pic1.png
file:///home/user/pic2.jpg
```

Unfortunately, accessing these lines is not easy from Thunderbird, because the string returned from [getAnyTransferData()](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsITransferable#getAnyTransferData()) is garbage. It looks like it was decoded using a wrong encoding. But once you know there's `text/uri-list` data on the clipboard you can ask for it again in `text/unicode` format. This works. It even has the advantage over Windows that you can attach multiple files in one go.

**Comment by qqlovekerry** [comment]
Hi @mganss , 
I have tried that. It seems in order to make it work, in Ubuntu, I have to run `xclip -o -t text/uri-list -selection clipboard` in the terminal before I use `From Clipboard` in Thunderbird, is that right?

**Comment by mganss** [comment]
@qqlovekerry No, you don't have to run xclip before pasting. That was just to illustrate how the X11 clipboard works.

**Comment by qqlovekerry** [comment]
OK, I think I got that. After upgrade with the new release, it works in Ubuntu. That is wonderful! Thanks very much!
I have another request. Is that possible to add keyboard shortcuts for this add-on. I feel it is more convenient to invoke the function by shortcuts instead of mouse clicking.

**Comment by mganss** [comment]
The shortcut is <kbd>Alt+Shift+V</kbd>.

**Comment by qqlovekerry** [comment]
Thanks very much for all your help!

**Comment by donillogit** [comment]
Doesn´t work with MacOS High Serria. I only get a textfile as attachment.

**Comment by mganss** [comment]
@donillogit I don't have a macOS machine available to me. It would be great if you could debug using the steps above in https://github.com/mganss/AttachFromClipboard/issues/2#issuecomment-457547223 and share your findings (possibly in a new issue).
