### ISSUE TITLE
It's not working with Thunderbird 68.*

### ISSUE THREAD

**Issue by twobaker** [mganss/AttachFromClipboard#3]
Hi,
Your plugin is very useful for me, but it doesn't work with new version Thunderbird 68.* Did you plan an update?

**Comment by mganss** [comment]
Yes, will update shortly.

**Comment by twobaker** [comment]
Thank you, I appreciate that.

**Comment by mganss** [comment]
Fixed in c09cf5c (1.1.68). Currently under review at AMO.
