### ISSUE TITLE
Shortcut customization

### ISSUE THREAD

**Issue by ghost** [mganss/AttachFromClipboard#4]
First of all, this is a great add-on! Thank you very much!

Is it possible to customize the paste shortcut? Customization by the user would probably be the best way to go, though at least for me `Ctrl`+`Shift`+`V` seems to be already much easier to type than `Alt`+`Shift`+`V`.

**Comment by mganss** [comment]
<kbd>Ctrl+Shift+V</kbd> is taken by "Paste without formatting". Customizing the shortcut is not possible from within the add-on but perhaps it's possible using [Dorando keyconfig](https://addons.thunderbird.net/en-US/thunderbird/addon/dorando-keyconfig/).
