### ISSUE TITLE
not working in version 70.0b4

### ISSUE THREAD

**Issue by jaisekjames** [mganss/AttachFromClipboard#5]
Addon installing in version 70.0b4. Paste menu/button active. But clicking nothing happens. Tried Shortcut, but opens View menu[alt + shift + v].

**Comment by mganss** [comment]
🙄 I won't investigate prior to the next stable release, though.

**Comment by mganss** [comment]
Updated for TB 78 in v1.78.0 (currently in review by Mozilla).
