### ISSUE TITLE
Change shortcut

### ISSUE THREAD

**Issue by goblatore** [mganss/AttachFromClipboard#6]
I dont see any option to change default shortcut "ALT+SHIFT+V" to something else.
Is it possible?
Bye
Giacomo

**Comment by mganss** [comment]
No, this is not currently possible.

**Comment by goblatore** [comment]
Ok I did it by myself by editing the main.xul (now I use "control alt" and "v") - needed it because in Italian layout (and I think in many others) ALT + key opens corresponing menu in menu bar...
Bye, Giacomo

**Comment by mganss** [comment]
You're right. I'll change it to <kbd>Ctrl + Alt + v</kbd>.
