### ISSUE TITLE
not working with TB 78.1.1

### ISSUE THREAD

**Issue by twobaker** [mganss/AttachFromClipboard#7]
Doesn't work with new version TB 78.1.1. Would be nice to have this very helpful AddOn again

**Comment by ameier3** [comment]
This is a very useful addon and I use it every day. Please provide an update to be comaptibe with Thunderbird 78.

**Comment by nietseb** [comment]
This is a very useful addon and I use it every day. Please provide an update to be comaptibe with Thunderbird 78. +1

**Comment by mganss** [comment]
Updated for TB 78 in v1.78.0. Currently under review by Mozilla.
